# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0003_auto_20171018_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
