# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0004_auto_20171019_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='details',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
    ]
